version: '3'

services:
  api:
    build:
      context: ./api  # The Dockerfile for the API is in the ./api folder
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models  # Mount the models directory from the host to the container
    networks:
      - app-network

  app:
    build:
      context: ./app  # The Dockerfile for the Streamlit app is in the ./app folder
    container_name: app
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
